### ISSUE TITLE
Cannot use it in electron applications

### ISSUE THREAD

**Issue by DinoscapeProgramming** [thoriqazzikraa/spotifydl#1]
Whenever I try to use this package in my electron applications I get the following errors:

```js
{
    "message": "Request failed with status code 403",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 403\n    at settle (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:1967:12)\n    at XMLHttpRequest.onloadend (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3358:7)\n    at Axios.request (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3877:41)\n    at async downloads (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:42:22)\n    at async downloadTrack (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:135:28)\n    at async <anonymous>:1:1",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Origin": "https://spotifydown.com",
            "Referer": "https://spotifydown.com/"
        },
        "method": "get",
        "url": "https://api.spotifydown.com/download/6GpyfvNqCPGdwWNgmSLp3D"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 403
}
```

and 
```js
{
    "status": false,
    "message": "Unknown error occurred!\n\nAxiosError: Request failed with status code 403"
}
```

I tried it on my web server and it works perfectly fine. I don't know what the issue is, but I hope you can fix it. (I'm using the latest version of electron (v28.2.0) and spotify-dl (v1.0.11))

**Comment by thoriqazzikraa** [comment]
> Whenever I try to use this package in my electron applications I get the following errors:
> 
> ```js
> {
>     "message": "Request failed with status code 403",
>     "name": "AxiosError",
>     "stack": "AxiosError: Request failed with status code 403\n    at settle (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:1967:12)\n    at XMLHttpRequest.onloadend (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3358:7)\n    at Axios.request (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3877:41)\n    at async downloads (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:42:22)\n    at async downloadTrack (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:135:28)\n    at async <anonymous>:1:1",
>     "config": {
>         "transitional": {
>             "silentJSONParsing": true,
>             "forcedJSONParsing": true,
>             "clarifyTimeoutError": false
>         },
>         "adapter": [
>             "xhr",
>             "http"
>         ],
>         "transformRequest": [
>             null
>         ],
>         "transformResponse": [
>             null
>         ],
>         "timeout": 0,
>         "xsrfCookieName": "XSRF-TOKEN",
>         "xsrfHeaderName": "X-XSRF-TOKEN",
>         "maxContentLength": -1,
>         "maxBodyLength": -1,
>         "env": {},
>         "headers": {
>             "Accept": "application/json, text/plain, */*",
>             "Origin": "https://spotifydown.com",
>             "Referer": "https://spotifydown.com/"
>         },
>         "method": "get",
>         "url": "https://api.spotifydown.com/download/6GpyfvNqCPGdwWNgmSLp3D"
>     },
>     "code": "ERR_BAD_REQUEST",
>     "status": 403
> }
> ```
> 
> and
> 
> ```js
> {
>     "status": false,
>     "message": "Unknown error occurred!\n\nAxiosError: Request failed with status code 403"
> }
> ```
> 
> I tried it on my web server and it works perfectly fine. I don't know what the issue is, but I hope you can fix it. (I'm using the latest version of electron (v28.2.0) and spotify-dl (v1.0.11))

sorry for late reply bro
it's cloud flare error i think, maybe this website that i use to scrape is block on your server/country

**Comment by thoriqazzikraa** [comment]
> Whenever I try to use this package in my electron applications I get the following errors:
> 
> ```js
> {
>     "message": "Request failed with status code 403",
>     "name": "AxiosError",
>     "stack": "AxiosError: Request failed with status code 403\n    at settle (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:1967:12)\n    at XMLHttpRequest.onloadend (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3358:7)\n    at Axios.request (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3877:41)\n    at async downloads (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:42:22)\n    at async downloadTrack (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:135:28)\n    at async <anonymous>:1:1",
>     "config": {
>         "transitional": {
>             "silentJSONParsing": true,
>             "forcedJSONParsing": true,
>             "clarifyTimeoutError": false
>         },
>         "adapter": [
>             "xhr",
>             "http"
>         ],
>         "transformRequest": [
>             null
>         ],
>         "transformResponse": [
>             null
>         ],
>         "timeout": 0,
>         "xsrfCookieName": "XSRF-TOKEN",
>         "xsrfHeaderName": "X-XSRF-TOKEN",
>         "maxContentLength": -1,
>         "maxBodyLength": -1,
>         "env": {},
>         "headers": {
>             "Accept": "application/json, text/plain, */*",
>             "Origin": "https://spotifydown.com",
>             "Referer": "https://spotifydown.com/"
>         },
>         "method": "get",
>         "url": "https://api.spotifydown.com/download/6GpyfvNqCPGdwWNgmSLp3D"
>     },
>     "code": "ERR_BAD_REQUEST",
>     "status": 403
> }
> ```
> 
> and
> 
> ```js
> {
>     "status": false,
>     "message": "Unknown error occurred!\n\nAxiosError: Request failed with status code 403"
> }
> ```
> 
> I tried it on my web server and it works perfectly fine. I don't know what the issue is, but I hope you can fix it. (I'm using the latest version of electron (v28.2.0) and spotify-dl (v1.0.11))

hi, i'm just update this module,  i'm adding
```js
downloads2,
downloadTrack2,
downloadAlbum2
```

please use this one instead the first one, i hope this website not get block in your country

**Comment by DinoscapeProgramming** [comment]
> > Whenever I try to use this package in my electron applications I get the following errors:
> > ```js
> > {
> >     "message": "Request failed with status code 403",
> >     "name": "AxiosError",
> >     "stack": "AxiosError: Request failed with status code 403\n    at settle (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:1967:12)\n    at XMLHttpRequest.onloadend (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3358:7)\n    at Axios.request (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3877:41)\n    at async downloads (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:42:22)\n    at async downloadTrack (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:135:28)\n    at async <anonymous>:1:1",
> >     "config": {
> >         "transitional": {
> >             "silentJSONParsing": true,
> >             "forcedJSONParsing": true,
> >             "clarifyTimeoutError": false
> >         },
> >         "adapter": [
> >             "xhr",
> >             "http"
> >         ],
> >         "transformRequest": [
> >             null
> >         ],
> >         "transformResponse": [
> >             null
> >         ],
> >         "timeout": 0,
> >         "xsrfCookieName": "XSRF-TOKEN",
> >         "xsrfHeaderName": "X-XSRF-TOKEN",
> >         "maxContentLength": -1,
> >         "maxBodyLength": -1,
> >         "env": {},
> >         "headers": {
> >             "Accept": "application/json, text/plain, */*",
> >             "Origin": "https://spotifydown.com",
> >             "Referer": "https://spotifydown.com/"
> >         },
> >         "method": "get",
> >         "url": "https://api.spotifydown.com/download/6GpyfvNqCPGdwWNgmSLp3D"
> >     },
> >     "code": "ERR_BAD_REQUEST",
> >     "status": 403
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```js
> > {
> >     "status": false,
> >     "message": "Unknown error occurred!\n\nAxiosError: Request failed with status code 403"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried it on my web server and it works perfectly fine. I don't know what the issue is, but I hope you can fix it. (I'm using the latest version of electron (v28.2.0) and spotify-dl (v1.0.11))
> 
> hi, i'm just update this module, i'm adding
> 
> ```js
> downloads2,
> downloadTrack2,
> downloadAlbum2
> ```
> 
> please use this one instead the first one, i hope this website not get block in your country

Thank you very much for this change! :)

> > Whenever I try to use this package in my electron applications I get the following errors:
> > ```js
> > {
> >     "message": "Request failed with status code 403",
> >     "name": "AxiosError",
> >     "stack": "AxiosError: Request failed with status code 403\n    at settle (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:1967:12)\n    at XMLHttpRequest.onloadend (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3358:7)\n    at Axios.request (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3877:41)\n    at async downloads (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:42:22)\n    at async downloadTrack (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:135:28)\n    at async <anonymous>:1:1",
> >     "config": {
> >         "transitional": {
> >             "silentJSONParsing": true,
> >             "forcedJSONParsing": true,
> >             "clarifyTimeoutError": false
> >         },
> >         "adapter": [
> >             "xhr",
> >             "http"
> >         ],
> >         "transformRequest": [
> >             null
> >         ],
> >         "transformResponse": [
> >             null
> >         ],
> >         "timeout": 0,
> >         "xsrfCookieName": "XSRF-TOKEN",
> >         "xsrfHeaderName": "X-XSRF-TOKEN",
> >         "maxContentLength": -1,
> >         "maxBodyLength": -1,
> >         "env": {},
> >         "headers": {
> >             "Accept": "application/json, text/plain, */*",
> >             "Origin": "https://spotifydown.com",
> >             "Referer": "https://spotifydown.com/"
> >         },
> >         "method": "get",
> >         "url": "https://api.spotifydown.com/download/6GpyfvNqCPGdwWNgmSLp3D"
> >     },
> >     "code": "ERR_BAD_REQUEST",
> >     "status": 403
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```js
> > {
> >     "status": false,
> >     "message": "Unknown error occurred!\n\nAxiosError: Request failed with status code 403"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried it on my web server and it works perfectly fine. I don't know what the issue is, but I hope you can fix it. (I'm using the latest version of electron (v28.2.0) and spotify-dl (v1.0.11))
> 
> sorry for late reply bro it's cloud flare error i think, maybe this website that i use to scrape is block on your server/country



> > Whenever I try to use this package in my electron applications I get the following errors:
> > ```js
> > {
> >     "message": "Request failed with status code 403",
> >     "name": "AxiosError",
> >     "stack": "AxiosError: Request failed with status code 403\n    at settle (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:1967:12)\n    at XMLHttpRequest.onloadend (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3358:7)\n    at Axios.request (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\axios\\dist\\node\\axios.cjs:3877:41)\n    at async downloads (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:42:22)\n    at async downloadTrack (C:\\Users\\email\\OneDrive\\Desktop\\Spotify Offline\\node_modules\\@nechlophomeriaa\\spotifydl\\src\\index.js:135:28)\n    at async <anonymous>:1:1",
> >     "config": {
> >         "transitional": {
> >             "silentJSONParsing": true,
> >             "forcedJSONParsing": true,
> >             "clarifyTimeoutError": false
> >         },
> >         "adapter": [
> >             "xhr",
> >             "http"
> >         ],
> >         "transformRequest": [
> >             null
> >         ],
> >         "transformResponse": [
> >             null
> >         ],
> >         "timeout": 0,
> >         "xsrfCookieName": "XSRF-TOKEN",
> >         "xsrfHeaderName": "X-XSRF-TOKEN",
> >         "maxContentLength": -1,
> >         "maxBodyLength": -1,
> >         "env": {},
> >         "headers": {
> >             "Accept": "application/json, text/plain, */*",
> >             "Origin": "https://spotifydown.com",
> >             "Referer": "https://spotifydown.com/"
> >         },
> >         "method": "get",
> >         "url": "https://api.spotifydown.com/download/6GpyfvNqCPGdwWNgmSLp3D"
> >     },
> >     "code": "ERR_BAD_REQUEST",
> >     "status": 403
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```js
> > {
> >     "status": false,
> >     "message": "Unknown error occurred!\n\nAxiosError: Request failed with status code 403"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I tried it on my web server and it works perfectly fine. I don't know what the issue is, but I hope you can fix it. (I'm using the latest version of electron (v28.2.0) and spotify-dl (v1.0.11))
> 
> hi, i'm just update this module, i'm adding
> 
> ```js
> downloads2,
> downloadTrack2,
> downloadAlbum2
> ```
> 
> please use this one instead the first one, i hope this website not get block in your country

Thank you very much for the change! :)
Seems to work now

Though, I've already fixed this issue by relaying the request to SpotifyDown to a server in the US.
