### ISSUE TITLE
with typescript

### ISSUE THREAD

**Issue by uris173** [thoriqazzikraa/spotifydl#2]
I can't use it with typescript, do you have a type declaration package?

**Comment by thoriqazzikraa** [comment]
unfortunately no, i will try to add ts for the next update

**Comment by uris173** [comment]
> к сожалению нет, я постараюсь добавить ts в следующем обновлении
I will be very grateful for this. thank you very much for the answer

**Comment by thoriqazzikraa** [comment]
> I can't use it with typescript, do you have a type declaration package?

bro what module you using in your app, esm or cjs?

**Comment by uris173** [comment]
bro, thanks for not leaving this.
esm module in my app

**Comment by uris173** [comment]
> > I can't use it with typescript, do you have a type declaration package?
> 
> bro what module you using in your app, esm or cjs?

bro, thanks for not leaving this.
esm module in my app

**Comment by thoriqazzikraa** [comment]
> > > I can't use it with typescript, do you have a type declaration package?
> > 
> > 
> > bro what module you using in your app, esm or cjs?
> 
> bro, thanks for not leaving this. esm module in my app

that's why is not working, i use cjs
i think i will make for esm soon
i'll be back

**Comment by thoriqazzikraa** [comment]
> > > I can't use it with typescript, do you have a type declaration package?
> > 
> > 
> > bro what module you using in your app, esm or cjs?
> 
> bro, thanks for not leaving this. esm module in my app

updated, check it now, please tell me if it's working, cause idk how to make cjs and esm working in the same package

**Comment by uris173** [comment]
> > > > I can't use it with typescript, do you have a type declaration package?
> > > 
> > > 
> > > bro what module you using in your app, esm or cjs?
> > 
> > 
> > bro, thanks for not leaving this. esm module in my app
> 
> updated, check it now, please tell me if it's working, cause idk how to make cjs and esm working in the same package

can I tell you the exact answer about the update this week?

**Comment by thoriqazzikraa** [comment]
> > > > > I can't use it with typescript, do you have a type declaration package?
> > > > 
> > > > 
> > > > bro what module you using in your app, esm or cjs?
> > > 
> > > 
> > > bro, thanks for not leaving this. esm module in my app
> > 
> > 
> > updated, check it now, please tell me if it's working, cause idk how to make cjs and esm working in the same package
> 
> can I tell you the exact answer about the update this week?

i make the module support for esm and cjs
i've tried with cjs and it's working
and my friend tried with esm and it's working too

**Comment by thoriqazzikraa** [comment]
> > > > > I can't use it with typescript, do you have a type declaration package?
> > > > 
> > > > 
> > > > bro what module you using in your app, esm or cjs?
> > > 
> > > 
> > > bro, thanks for not leaving this. esm module in my app
> > 
> > 
> > updated, check it now, please tell me if it's working, cause idk how to make cjs and esm working in the same package
> 
> can I tell you the exact answer about the update this week?

go try it, and let me know if it's work

**Comment by thoriqazzikraa** [comment]
> > > > > I can't use it with typescript, do you have a type declaration package?
> > > > 
> > > > 
> > > > bro what module you using in your app, esm or cjs?
> > > 
> > > 
> > > bro, thanks for not leaving this. esm module in my app
> > 
> > 
> > updated, check it now, please tell me if it's working, cause idk how to make cjs and esm working in the same package
> 
> can I tell you the exact answer about the update this week?

yo is it work?

**Comment by uris173** [comment]
> > > > > > I can't use it with typescript, do you have a type declaration package?
> > > > > 
> > > > > 
> > > > > bro what module you using in your app, esm or cjs?
> > > > 
> > > > 
> > > > bro, thanks for not leaving this. esm module in my app
> > > 
> > > 
> > > updated, check it now, please tell me if it's working, cause idk how to make cjs and esm working in the same package
> > 
> > can I tell you the exact answer about the update this week?
> 
> yo is it work?


can I tell you the answer on sunday?  I have work during the day, and in the evening I’m wildly tired

**Comment by uris173** [comment]
> > > > > > I can't use it with typescript, do you have a type declaration package?
> > > > > 
> > > > > 
> > > > > bro what module you using in your app, esm or cjs?
> > > > 
> > > > 
> > > > bro, thanks for not leaving this. esm module in my app
> > > 
> > > 
> > > updated, check it now, please tell me if it's working, cause idk how to make cjs and esm working in the same package
> > 
> > 
> > can I tell you the exact answer about the update this week?
> 
> yo is it work?

hi bro. I installed the package, but unfortunately @types are missing.

**Comment by thoriqazzikraa** [comment]
> > > > > > > I can't use it with typescript, do you have a type declaration package?
> > > > > > 
> > > > > > 
> > > > > > bro what module you using in your app, esm or cjs?
> > > > > 
> > > > > 
> > > > > bro, thanks for not leaving this. esm module in my app
> > > > 
> > > > 
> > > > updated, check it now, please tell me if it's working, cause idk how to make cjs and esm working in the same package
> > > 
> > > 
> > > can I tell you the exact answer about the update this week?
> > 
> > 
> > yo is it work?
> 
> hi bro. I installed the package, but unfortunately @types are missing.

sorry bro, i will fix it soon, i'm really sorry, idk anything from typescript😭
give me couple days

**Comment by thoriqazzikraa** [comment]
> > > > > > > I can't use it with typescript, do you have a type declaration package?
> > > > > > 
> > > > > > 
> > > > > > bro what module you using in your app, esm or cjs?
> > > > > 
> > > > > 
> > > > > bro, thanks for not leaving this. esm module in my app
> > > > 
> > > > 
> > > > updated, check it now, please tell me if it's working, cause idk how to make cjs and esm working in the same package
> > > 
> > > 
> > > can I tell you the exact answer about the update this week?
> > 
> > 
> > yo is it work?
> 
> hi bro. I installed the package, but unfortunately @types are missing.

update, try it, please let me know is it exactly what you want?

**Comment by uris173** [comment]
> > > > > > > > I can't use it with typescript, do you have a type declaration package?
> > > > > > > 
> > > > > > > 
> > > > > > > bro what module you using in your app, esm or cjs?
> > > > > > 
> > > > > > 
> > > > > > bro, thanks for not leaving this. esm module in my app
> > > > > 
> > > > > 
> > > > > updated, check it now, please tell me if it's working, cause idk how to make cjs and esm working in the same package
> > > > 
> > > > 
> > > > can I tell you the exact answer about the update this week?
> > > 
> > > 
> > > yo is it work?
> > 
> > 
> > hi bro. I installed the package, but unfortunately @types are missing.
> 
> update, try it, please let me know is it exactly what you want?

Installed, I'm checking now

**Comment by uris173** [comment]
yes, that's what I need. Thanks a lot.
There is another question, with downloadTrack the answer is very long, about 7 seconds. Can you clarify why it took so long?

**Comment by thoriqazzikraa** [comment]
> yes, that's what I need. Thanks a lot. There is another question, with downloadTrack the answer is very long, about 7 seconds. Can you clarify why it took so long?

maybe website server idk, give it a try https://spotifydown.com/id

and first of all, they send the link of the audio which is not include metadata, so i'm using node-fetch to get buffer of the audio file, and i put metadata using node id3, that's it
umm, `downloadTrack2` is not taking too long because the audio file is included metadata, so i'm not using node id3 like `downloadTrack` but i think `downloadTrack2` have a problem from the website server i guess
