### ISSUE TITLE
I received a 403 error for some songs.

### ISSUE THREAD

**Issue by alirezaaghaeee** [thoriqazzikraa/spotifydl#3]
Error: StatusCodeError: 403 - "\n<html><head>\n<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\">\n<title>403 Forb
idden</title>\n</head>\n<body text=#000000 bgcolor=#ffffff>\n<h1>Error: Forbidden</h1>\n<h2>Your client does not have permission to ge
t URL <code>/api/token</code> from this server.</h2>\n<h2></h2>\n</body></html>\n"

**Comment by thoriqazzikraa** [comment]
> Error: StatusCodeError: 403 - "\n\n<meta http-equiv="content-type" content="text/html;charset=utf-8">\n<title>403 Forb idden</title>\n\n\n
> 
> # Error: Forbidden
> \n
> ## Your client does not have permission to ge
> t URL `/api/token` from this server.
> \n
> \n\n"

which one? downloadTrack version 1 or version 2?

**Comment by thoriqazzikraa** [comment]
> Error: StatusCodeError: 403 - "\n\n<meta http-equiv="content-type" content="text/html;charset=utf-8">\n<title>403 Forb idden</title>\n\n\n
> 
> # Error: Forbidden
> \n
> ## Your client does not have permission to ge
> t URL `/api/token` from this server.
> \n
> \n\n"

hi there

**Comment by thoriqazzikraa** [comment]
i will close this issue since you not reply

**Comment by alirezaaghaeee** [comment]
for both

**Comment by thoriqazzikraa** [comment]
> for both

use downloadTrack3, error maybe from the server
